# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contextitems',
            name='course_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contextitems',
            name='org_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contextitems',
            name='path',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contextitems',
            name='user_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='logitems',
            name='accept_language',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='logitems',
            name='agent',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='logitems',
            name='event',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='logitems',
            name='event_type',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='logitems',
            name='host',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='logitems',
            name='ip',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='logitems',
            name='name',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='logitems',
            name='page',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='logitems',
            name='referer',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='logitems',
            name='session',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='logitems',
            name='time',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='logitems',
            name='username',
            field=models.CharField(max_length=10000),
        ),
    ]
