# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_auto_20170829_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logitems',
            name='event',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='logitems',
            name='ip',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='logitems',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='logitems',
            name='username',
            field=models.CharField(max_length=1000),
        ),
    ]
