# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0005_auto_20170829_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logitems',
            name='event',
            field=models.TextField(max_length=500),
        ),
    ]
