# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 19:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0006_auto_20170829_0058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logitems',
            name='accept_language',
        ),
        migrations.RemoveField(
            model_name='logitems',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='logitems',
            name='event',
        ),
        migrations.RemoveField(
            model_name='logitems',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='logitems',
            name='host',
        ),
        migrations.RemoveField(
            model_name='logitems',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='logitems',
            name='page',
        ),
        migrations.RemoveField(
            model_name='logitems',
            name='referer',
        ),
        migrations.RemoveField(
            model_name='logitems',
            name='session',
        ),
        migrations.RemoveField(
            model_name='logitems',
            name='time',
        ),
    ]
