# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0010_auto_20170829_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contextitems',
            name='user_id',
            field=models.CharField(default='', max_length=10),
        ),
    ]
