# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0011_auto_20170829_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='logitems',
            name='accept_language',
            field=models.CharField(default='-1', max_length=200),
        ),
        migrations.AddField(
            model_name='logitems',
            name='agent',
            field=models.CharField(default='-1', max_length=200),
        ),
        migrations.AddField(
            model_name='logitems',
            name='event',
            field=models.TextField(default='-1', max_length=500),
        ),
        migrations.AddField(
            model_name='logitems',
            name='event_type',
            field=models.CharField(default='-1', max_length=200),
        ),
        migrations.AddField(
            model_name='logitems',
            name='host',
            field=models.CharField(default='-1', max_length=200),
        ),
        migrations.AddField(
            model_name='logitems',
            name='ip',
            field=models.CharField(default='-1', max_length=200),
        ),
        migrations.AddField(
            model_name='logitems',
            name='page',
            field=models.CharField(default='-1', max_length=200),
        ),
        migrations.AddField(
            model_name='logitems',
            name='referer',
            field=models.CharField(default='-1', max_length=200),
        ),
        migrations.AddField(
            model_name='logitems',
            name='session',
            field=models.CharField(default='-1', max_length=200),
        ),
        migrations.AddField(
            model_name='logitems',
            name='time',
            field=models.CharField(default='-1', max_length=200),
        ),
        migrations.AlterField(
            model_name='contextitems',
            name='course_id',
            field=models.TextField(default='-1'),
        ),
        migrations.AlterField(
            model_name='contextitems',
            name='org_id',
            field=models.TextField(default='-1'),
        ),
        migrations.AlterField(
            model_name='contextitems',
            name='path',
            field=models.TextField(default='-1'),
        ),
        migrations.AlterField(
            model_name='contextitems',
            name='user_id',
            field=models.CharField(default='-1', max_length=10),
        ),
    ]
