# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0013_auto_20170829_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logitems',
            name='context',
        ),
        migrations.AlterField(
            model_name='contextitems',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
