# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0014_auto_20170829_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logitems',
            name='event',
        ),
        migrations.RemoveField(
            model_name='logitems',
            name='session',
        ),
        migrations.AlterField(
            model_name='logitems',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
