# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0015_auto_20170829_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contextitems',
            name='id',
        ),
        migrations.AddField(
            model_name='contextitems',
            name='serial_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
